version: '2'

services:
    nginx:
        image: nginx:1.10.2
        ports:
            - 80:80
        restart: always
        volumes:
            - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        links:
            - php
        depends_on:
            - php
    php:
        build: docker/php
        expose:
            - 9000
        restart: always
        volumes:
            - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/var/www/html
        environment:
            XDEBUG_CONFIG: remote_host=192.168.1.13